export enum JobsEnum {
    APP_VERSION_UPDATE_MSG = 'APP_VERSION_UPDATE_MSG',
    SOFTWARE_DOWNLOAD_MSG = 'SOFTWARE_DOWNLOAD_MSG',
    REQ_LOG_MSG = 'REQ_LOG_MSG',
    REBOOT_MSG = 'REBOOT_MSG',
    SETTLEMENT_REQ_MSG = 'SETTLEMENT_REQ_MSG'
}