import { CurrencyCode } from './currency-code.model';

export var currencies: CurrencyCode [] = [
    {code:"AFN",country:"Afghanistan Afghanis – AFN"},
    {code:"ALL",country:"Albania Leke – ALL"},
    {code:"DZD",country:"Algeria Dinars – DZD"},
    {code:"ARS",country:"Argentina Pesos – ARS"},
    {code:"AUD",country:"Australia Dollars – AUD"},
    {code:"ATS",country:"Austria Schillings – ATS"},
    {code:"BSD",country:"Bahamas Dollars – BSD"},
    {code:"BHD",country:"Bahrain Dinars – BHD"},
    {code:"BDT",country:"Bangladesh Taka – BDT"},
    {code:"BBD",country:"Barbados Dollars – BBD"},
    {code:"BEF",country:"Belgium Francs – BEF"},
    {code:"BMD",country:"Bermuda Dollars – BMD"},
    {code:"BRL",country:"Brazil Reais – BRL"},
    {code:"BGN",country:"Bulgaria Leva – BGN"},
    {code:"CAD",country:"Canada Dollars – CAD"},
    {code:"XOF",country:"CFA BCEAO Francs – XOF"},
    {code:"XAF",country:"CFA BEAC Francs – XAF"},
    {code:"CLP",country:"Chile Pesos – CLP"},
    {code:"CNY",country:"China Yuan Renminbi – CNY"},
    {code:"COP",country:"Colombia Pesos – COP"},
    {code:"XPF",country:"CFP Francs – XPF"},
    {code:"CRC",country:"Costa Rica Colones – CRC"},
    {code:"HRK",country:"Croatia Kuna – HRK"},
    {code:"CYP",country:"Cyprus Pounds – CYP"},
    {code:"CZK",country:"Czech Republic Koruny – CZK"},
    {code:"DKK",country:"Denmark Kroner – DKK"},
    {code:"DEM",country:"Deutsche (Germany) Marks – DEM"},
    {code:"DOP",country:"Dominican Republic Pesos – DOP"},
    {code:"NLG",country:"Dutch (Netherlands) Guilders - NLG"},
    {code:"XCD",country:"Eastern Caribbean Dollars – XCD"},
    {code:"EGP",country:"Egypt Pounds – EGP"},
    {code:"EEK",country:"Estonia Krooni – EEK"},
    {code:"EUR",country:"Euro – EUR"},
    {code:"FJD",country:"Fiji Dollars – FJD"},
    {code:"FIM",country:"Finland Markkaa – FIM"},
    {code:"FRF",country:"France Francs – FRF"},
    {code:"DEM",country:"Germany Deutsche Marks – DEM"},
    {code:"XAU",country:"Gold Ounces – XAU"},
    {code:"GRD",country:"Greece Drachmae – GRD"},
    {code:"GTQ",country:"Guatemalan Quetzal – GTQ"},
    {code:"NLG",country:"Holland (Netherlands) Guilders – NLG"},
    {code:"HKD",country:"Hong Kong Dollars – HKD"},
    {code:"HUF",country:"Hungary Forint – HUF"},
    {code:"ISK",country:"Iceland Kronur – ISK"},
    {code:"XDR",country:"IMF Special Drawing Right – XDR"},
    {code:"INR",country:"India Rupees – INR"},
    {code:"IDR",country:"Indonesia Rupiahs – IDR"},
    {code:"IRR",country:"Iran Rials – IRR"},
    {code:"IQD",country:"Iraq Dinars – IQD"},
    {code:"IEP",country:"Ireland Pounds – IEP"},
    {code:"ILS",country:"Israel New Shekels – ILS"},
    {code:"ITL",country:"Italy Lire – ITL"},
    {code:"JMD",country:"Jamaica Dollars – JMD"},
    {code:"JPY",country:"Japan Yen – JPY"},
    {code:"JOD",country:"Jordan Dinars – JOD"},
    {code:"KES",country:"Kenya Shillings – KES"},
    {code:"KRW",country:"Korea (South) Won – KRW"},
    {code:"KWD",country:"Kuwait Dinars – KWD"},
    {code:"LBP",country:"Lebanon Pounds – LBP"},
    {code:"LUF",country:"Luxembourg Francs – LUF"},
    {code:"MYR",country:"Malaysia Ringgits – MYR"},
    {code:"MTL",country:"Malta Liri – MTL"},
    {code:"MUR",country:"Mauritius Rupees – MUR"},
    {code:"MXN",country:"Mexico Pesos – MXN"},
    {code:"MAD",country:"Morocco Dirhams – MAD"},
    {code:"NLG",country:"Netherlands Guilders – NLG"},
    {code:"NZD",country:"New Zealand Dollars – NZD"},
    {code:"NOK",country:"Norway Kroner – NOK"},
    {code:"OMR",country:"Oman Rials – OMR"},
    {code:"PKR",country:"Pakistan Rupees – PKR"},
    {code:"XPD",country:"Palladium Ounces – XPD"},
    {code:"PEN",country:"Peru Nuevos Soles – PEN"},
    {code:"PHP",country:"Philippines Pesos – PHP"},
    {code:"XPT",country:"Platinum Ounces – XPT"},
    {code:"PLN",country:"Poland Zlotych – PLN"},
    {code:"PTE",country:"Portugal Escudos – PTE"},
    {code:"QAR",country:"Qatar Riyals – QAR"},
    {code:"RON",country:"Romania New Lei – RON"},
    {code:"ROL",country:"Romania Lei – ROL"},
    {code:"RUB",country:"Russia Rubles – RUB"},
    {code:"SAR",country:"Saudi Arabia Riyals – SAR"},
    {code:"XAG",country:"Silver Ounces – XAG"},
    {code:"SGD",country:"Singapore Dollars – SGD"},
    {code:"SKK",country:"Slovakia Koruny – SKK"},
    {code:"SIT",country:"Slovenia Tolars – SIT"},
    {code:"ZAR",country:"South Africa Rand – ZAR"},
    {code:"KRW",country:"South Korea Won – KRW"},
    {code:"ESP",country:"Spain Pesetas – ESP"},
    {code:"XDR",country:"Special Drawing Rights (IMF) – XDR"},
    {code:"LKR",country:"Sri Lanka Rupees – LKR"},
    {code:"SDD",country:"Sudan Dinars – SDD"},
    {code:"SEK",country:"Sweden Kronor – SEK"},
    {code:"CHF",country:"Switzerland Francs – CHF"},
    {code:"TWD",country:"Taiwan New Dollars – TWD"},
    {code:"THB",country:"Thailand Baht – THB"},
    {code:"TTD",country:"Trinidad and Tobago Dollars – TTD"},
    {code:"TND",country:"Tunisia Dinars – TND"},
    {code:"TRY",country:"Turkey New Lira – TRY"},
    {code:"AED",country:"United Arab Emirates Dirhams – AED"},
    {code:"GBP",country:"United Kingdom Pounds – GBP"},
    {code:"USD",country:"United States Dollars – USD"},
    {code:"VEB",country:"Venezuela Bolivares – VEB"},
    {code:"VND",country:"Vietnam Dong – VND"},
    {code:"ZMK",country:"Zambia Kwacha – ZMK"},
    ]