export enum RolesEnum {
    AZ_ROOT_ADMIN = 'AZ_ROOT_ADMIN',
    AZ_ADMIN = 'AZ_ADMIN',
    AZ_SUPPORT = 'AZ_SUPPORT',
    MERCHANT_ADMIN = 'MERCHANT_ADMIN',
    MERCHANT_SUPERVISOR = 'MERCHANT_SUPERVISOR',
    MERCHANT_USER = 'MERCHANT_USER'
}